name: Nextjs CI

on:
 push:
   branches: [main]

jobs:
 build_and_package:
   runs-on: ubuntu-latest
   steps:
       
     - name: Checkout code
       uses: actions/checkout@v2
   
     - name: Setup tmate session
       if: ${{ failure() }}
       uses: mxschmitt/action-tmate@v3   
       with:
        limit-access-to-actor: false
     
     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 10
     
     - name: Install dependencies
       run: npm install
     
     - name: Build
       run: npm run build
