name: Multiple Labels Example

on:
  push:
    branches:
      - main

jobs:
  job-with-label1:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Runner 1
      run: echo "this job will run on self-hosted ubuntu 20.04"

  job-with-label2:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Runner 2
      run: echo "this job will run on self-hosted ubuntu 22.04"
