name: Nextjs CI

on:
  push:
    branches: [main]

jobs:
  build:
    uses: mohamed1199/ci-templates/.github/workflows/nextjs-ci.yaml@main

  upload-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload .nextjs 
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-artifact
          path: .next



