name: Nextjs CI

on:
 push:
   branches: [main]

jobs:
 build_and_package:
   runs-on: ubuntu-latest
   steps:
     
     - name: Checkout code
       uses: actions/checkout@v2
     
     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 10

     - name: Debug
       uses: raven-actions/debug@v1
     
     - name: Install dependencies
       run: npm install
     
     - name: Build
       run: npm run build

     - name: Archive npm failure logs
       uses: actions/upload-artifact@v2
       if: failure()
       with:
         name: npm-logs
         path: ~/.npm/_logs   


