name: Remove Artifact 

on: [push]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create test file
      rund: echo hello > test.txt && exit

    - uses: actions/upload-artifact@v4
      with:
          name: my-artifact
          path: test.txt

    - uses: geekyeggo/delete-artifact@v4
      with:
          name: my-artifact
