name: Publish to GitHub Packages

on:
  push:
    branches: [main]

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: '14'
    
      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: "*.tgz"
  
  publish:
    runs-on: ubuntu-latest
    name: "Publish to GitHub Packages"
    needs: [build_and_package]

    steps:
      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Set up Node.js and publish
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
          scope: "@mohamed1199"

      - run: echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> $HOME/.npmrc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
