name: Nextjs CI debug

on:
 push:
   branches: [main]

jobs:
 build_and_package:
   runs-on: ubuntu-latest
   steps:

     - name: Initialize CodeQL
       uses: github/codeql-action/init@v2 
       with:
         languages: ${{ matrix.language }}
      
     - name: Checkout code
       uses: actions/checkout@v2
     
     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 10
     
     - name: Install dependencies
       run: npm install
     
     - name: Build
       run: npm run build

       


