name: Nextjs CI debug

on:
 push:
   branches: [main]

jobs:
 build_and_package:
   runs-on: ubuntu-latest
   steps:
       
     - name: Checkout code
       uses: actions/checkout@v2

     - name: continue
       run: touch continue

     - name: Setup upterm session
       uses: lhotari/action-upterm@v1
     
     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 10
     
     - name: Install dependencies
       run: npm install
     
     - name: Build
       run: npm run build


